---
elasticsearch:
  host: localhost
  port: 9200
homes:
- path: c:/programdata/geographix/projects
  active: true
  label: red
  scan_date: 2015-04-16 06:27:40.688772000 -07:00
  scan_deep: false
  projects:
  - path: c:/programdata/geographix/projects/California
    label: red
    active: true
    extract_code: 117
    scan_date: 
  - path: c:/programdata/geographix/projects/eiq_test
    label: red
    active: true
    extract_code: 1080
    scan_date: 
  - path: c:/programdata/geographix/projects/KS_BOURBON
    label: red
    active: true
    extract_code: 1
    scan_date: 
  - path: c:/programdata/geographix/projects/KS_HARPER
    label: red
    active: true
    extract_code: 16381
    scan_date: 
  - path: c:/programdata/geographix/projects/Stratton
    label: red
    active: true
    extract_code: 1
    scan_date: 
- path: c:/fake_ggx_home
  active: true
  label: zzz
  scan_date: 2015-04-16 06:27:40.688772000 -07:00
  scan_deep: true
  projects:
  - path: c:/fake_ggx_home/KS_HARPER
    label: zzz
    active: true
    extract_code: 49
    scan_date: 
