---
:elasticsearch:
  :host: localhost
  :port: 9200
:homes:
- :path: c:/programdata/geographix/projects
  :active: true
  :label: blue
  :scan_date: 2015-02-08 13:35:36.129646000 -08:00
  :scan_deep: false
  :projects:
  - :path: c:/programdata/geographix/projects/California
    :label: blue
    :active: true
    :extracts: []
  - :path: c:/programdata/geographix/projects/eiq_test
    :label: blue
    :active: true
    :extracts: []
  - :path: c:/programdata/geographix/projects/KS_BOURBON
    :label: blue
    :active: true
    :extracts: []
  - :path: c:/programdata/geographix/projects/KS_HARPER
    :label: blue
    :active: true
    :extracts: []
  - :path: c:/programdata/geographix/projects/Stratton
    :label: blue
    :active: true
    :extracts: []
- :path: c:/temp
  :active: false
  :label: unlabeled
  :scan_date: 2015-02-08 14:16:31.746501000 -08:00
  :scan_deep: false
  :projects: []
